// <auto-generated />
using System;
using CommitAhead.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommitAhead.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommitAheadDbContext))]
    [Migration("20260807212501_UpdateAIUsageRecordIndexesForOwnerScope")]
    partial class UpdateAIUsageRecordIndexesForOwnerScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommitAhead.Domain.AIUsage.AIUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_cost");

                    b.Property<int?>("ActualInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("actual_input_tokens");

                    b.Property<int?>("ActualOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("actual_output_tokens");

                    b.Property<Guid?>("AnalysisDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_draft_id");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("command_type");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("OutcomeCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("outcome_code");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PricingVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pricing_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<decimal>("ReservedCost")
                        .HasColumnType("numeric")
                        .HasColumnName("reserved_cost");

                    b.Property<int>("ReservedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_input_tokens");

                    b.Property<int>("ReservedOutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_output_tokens");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique()
                        .HasFilter("status = 'Reserved'");

                    b.HasIndex("OwnerUserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OwnerUserId", "StartedAtUtc");

                    b.ToTable("ai_usage_records", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DiscardedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discarded_at_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("SourceType", "SourceId")
                        .IsUnique()
                        .HasFilter("status = 'Pending'");

                    b.ToTable("analysis_drafts", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.LinkProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedRationale")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("accepted_rationale");

                    b.Property<decimal?>("AcceptedWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("accepted_weight");

                    b.Property<Guid>("AnalysisDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_draft_id");

                    b.Property<string>("ProposedRationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proposed_rationale");

                    b.Property<decimal>("ProposedWeight")
                        .HasColumnType("numeric")
                        .HasColumnName("proposed_weight");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetStudyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_study_item_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDraftId");

                    b.HasIndex("TargetStudyItemId");

                    b.ToTable("link_proposals", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.StudyItemProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("accepted_category");

                    b.Property<string>("AcceptedDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("accepted_details");

                    b.Property<int?>("AcceptedImportance")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_importance");

                    b.Property<int?>("AcceptedInitialMastery")
                        .HasColumnType("integer")
                        .HasColumnName("accepted_initial_mastery");

                    b.PrimitiveCollection<string[]>("AcceptedTags")
                        .HasColumnType("text[]")
                        .HasColumnName("accepted_tags");

                    b.Property<string>("AcceptedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("accepted_title");

                    b.Property<Guid>("AnalysisDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_draft_id");

                    b.Property<string>("ProposedCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("proposed_category");

                    b.Property<string>("ProposedDetails")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("proposed_details");

                    b.Property<int>("ProposedImportance")
                        .HasColumnType("integer")
                        .HasColumnName("proposed_importance");

                    b.PrimitiveCollection<string[]>("ProposedTags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("proposed_tags");

                    b.Property<string>("ProposedTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proposed_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDraftId");

                    b.ToTable("study_item_proposals", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.SuggestionProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("accepted_payload");

                    b.Property<Guid>("AnalysisDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_draft_id");

                    b.Property<string>("ProposedPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("proposed_payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisDraftId");

                    b.ToTable("suggestion_proposals", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.CVPresentations.CVPresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("CertificationSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("certification_selections");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("date_format");

                    b.PrimitiveCollection<Guid[]>("EducationSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("education_selections");

                    b.PrimitiveCollection<Guid[]>("ExperienceSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("experience_selections");

                    b.Property<bool>("IncludeAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("include_address");

                    b.Property<bool>("IncludeEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("include_email");

                    b.Property<bool>("IncludePhone")
                        .HasColumnType("boolean")
                        .HasColumnName("include_phone");

                    b.Property<bool>("IncludePhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("include_photo");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<Guid[]>("LanguageSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("language_selections");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locale");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("PageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("page_limit");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.PrimitiveCollection<Guid[]>("ProfileLinkSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("profile_link_selections");

                    b.PrimitiveCollection<Guid[]>("ProjectSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("project_selections");

                    b.PrimitiveCollection<Guid[]>("SkillSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_selections");

                    b.Property<string>("SummaryOverrideMarkdown")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_override_markdown");

                    b.Property<string>("TargetMarket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_market");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_role");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProfessionalProfileId", "OwnerUserId");

                    b.ToTable("cv_presentations", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.EvidenceLinks.EvidenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rationale");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("TargetStudyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_study_item_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("TargetStudyItemId");

                    b.HasIndex("OwnerUserId", "TargetStudyItemId");

                    b.HasIndex("SourceType", "SourceId", "TargetStudyItemId")
                        .IsUnique();

                    b.ToTable("evidence_links", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supabase_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.InterviewNotes.InterviewNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.PrimitiveCollection<string[]>("Gaps")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("gaps");

                    b.Property<string>("InterviewRound")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("interview_round");

                    b.Property<Guid?>("JobAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_analysis_id");

                    b.PrimitiveCollection<string[]>("Lessons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("lessons");

                    b.Property<string>("OtherLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("other_label");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.PrimitiveCollection<string[]>("Questions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("questions");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("JobAnalysisId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("interview_notes", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("JobSource")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("job_source");

                    b.Property<string>("NotesMarkdown")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("notes_markdown");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("job_analyses", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobGap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_analysis_id");

                    b.Property<string>("MatchLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("match_level");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rationale");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("JobAnalysisId");

                    b.HasIndex("RequirementId", "JobAnalysisId");

                    b.ToTable("job_gaps", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_analysis_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("priority");

                    b.Property<string>("SourceExcerpt")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_excerpt");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("JobAnalysisId");

                    b.ToTable("job_requirements", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.CertificationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_id");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<int?>("IssuedAt")
                        .HasColumnType("integer")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuingOrganisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuing_organisation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("certification_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.EducationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degree");

                    b.Property<string>("DetailsMarkdown")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("details_markdown");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<int?>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("education_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Achievements")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("achievements");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("employment_type");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.PrimitiveCollection<Guid[]>("SkillIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_ids");

                    b.Property<int>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.Property<string>("SummaryMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_markdown");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("experience_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.LanguageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Certification")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("certification");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("language");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("proficiency");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("language_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SummaryMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_markdown");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("professional_profiles", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfileLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("profile_links", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProjectEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("description_markdown");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.PrimitiveCollection<Guid[]>("SkillIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_ids");

                    b.Property<int?>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("project_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_key");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Proficiency")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("proficiency");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId", "NormalizedKey")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<int>("InitialMastery")
                        .HasColumnType("integer")
                        .HasColumnName("initial_mastery");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("study_items", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfidenceRating")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_rating");

                    b.Property<string>("NotesMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("notes_markdown");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid>("StudyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_item_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyItemId");

                    b.ToTable("study_reviews", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Infrastructure.StudyItems.ScoringConfigOverrideRow", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("DemandWeight")
                        .HasColumnType("integer")
                        .HasColumnName("demand_weight");

                    b.Property<int>("ImportanceWeight")
                        .HasColumnType("integer")
                        .HasColumnName("importance_weight");

                    b.Property<int>("MasteryGapWeight")
                        .HasColumnType("integer")
                        .HasColumnName("mastery_gap_weight");

                    b.HasKey("OwnerUserId");

                    b.ToTable("scoring_config_overrides", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.AIUsage.AIUsageRecord", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.LinkProposal", b =>
                {
                    b.HasOne("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", null)
                        .WithMany("LinkProposals")
                        .HasForeignKey("AnalysisDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.StudyItemProposal", b =>
                {
                    b.HasOne("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", null)
                        .WithMany("StudyItemProposals")
                        .HasForeignKey("AnalysisDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.SuggestionProposal", b =>
                {
                    b.HasOne("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", null)
                        .WithMany("SuggestionProposals")
                        .HasForeignKey("AnalysisDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.CVPresentations.CVPresentation", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalProfileId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.EvidenceLinks.EvidenceLink", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommitAhead.Domain.StudyItems.StudyItem", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId", "TargetStudyItemId")
                        .HasPrincipalKey("OwnerUserId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.InterviewNotes.InterviewNote", b =>
                {
                    b.HasOne("CommitAhead.Domain.JobAnalyses.JobAnalysis", null)
                        .WithMany()
                        .HasForeignKey("JobAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobAnalysis", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobGap", b =>
                {
                    b.HasOne("CommitAhead.Domain.JobAnalyses.JobAnalysis", null)
                        .WithMany("Gaps")
                        .HasForeignKey("JobAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommitAhead.Domain.JobAnalyses.JobRequirement", null)
                        .WithMany()
                        .HasForeignKey("RequirementId", "JobAnalysisId")
                        .HasPrincipalKey("Id", "JobAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobRequirement", b =>
                {
                    b.HasOne("CommitAhead.Domain.JobAnalyses.JobAnalysis", null)
                        .WithMany("Requirements")
                        .HasForeignKey("JobAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.CertificationEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Certifications")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.EducationEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Education")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ExperienceEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Experience")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.LanguageEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Languages")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfileLink", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("ProfileLinks")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProjectEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Projects")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.Skill", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CommitAhead.Domain.StudyItems.PriorityOverride", "PriorityOverride", b1 =>
                        {
                            b1.Property<Guid>("StudyItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("priority_override_reason");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("priority_override_score");

                            b1.HasKey("StudyItemId");

                            b1.ToTable("study_items");

                            b1.WithOwner()
                                .HasForeignKey("StudyItemId");
                        });

                    b.Navigation("PriorityOverride");
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyReview", b =>
                {
                    b.HasOne("CommitAhead.Domain.StudyItems.StudyItem", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StudyItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Infrastructure.StudyItems.ScoringConfigOverrideRow", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.AnalysisDrafts.AnalysisDraft", b =>
                {
                    b.Navigation("LinkProposals");

                    b.Navigation("StudyItemProposals");

                    b.Navigation("SuggestionProposals");
                });

            modelBuilder.Entity("CommitAhead.Domain.JobAnalyses.JobAnalysis", b =>
                {
                    b.Navigation("Gaps");

                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Languages");

                    b.Navigation("ProfileLinks");

                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
