// <auto-generated />
using System;
using CommitAhead.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommitAhead.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommitAheadDbContext))]
    [Migration("20260730100425_AddStudyItems")]
    partial class AddStudyItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommitAhead.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supabase_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int>("Importance")
                        .HasColumnType("integer")
                        .HasColumnName("importance");

                    b.Property<int>("InitialMastery")
                        .HasColumnType("integer")
                        .HasColumnName("initial_mastery");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Status");

                    b.ToTable("study_items", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConfidenceRating")
                        .HasColumnType("integer")
                        .HasColumnName("confidence_rating");

                    b.Property<string>("NotesMarkdown")
                        .HasColumnType("text")
                        .HasColumnName("notes_markdown");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid>("StudyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_item_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyItemId");

                    b.ToTable("study_reviews", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Infrastructure.StudyItems.ScoringConfigOverrideRow", b =>
                {
                    b.Property<Guid>("OwnerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("DemandWeight")
                        .HasColumnType("integer")
                        .HasColumnName("demand_weight");

                    b.Property<int>("ImportanceWeight")
                        .HasColumnType("integer")
                        .HasColumnName("importance_weight");

                    b.Property<int>("MasteryGapWeight")
                        .HasColumnType("integer")
                        .HasColumnName("mastery_gap_weight");

                    b.HasKey("OwnerUserId");

                    b.ToTable("scoring_config_overrides", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.OwnsOne("CommitAhead.Domain.StudyItems.PriorityOverride", "PriorityOverride", b1 =>
                        {
                            b1.Property<Guid>("StudyItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("priority_override_reason");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("priority_override_score");

                            b1.HasKey("StudyItemId");

                            b1.ToTable("study_items");

                            b1.WithOwner()
                                .HasForeignKey("StudyItemId");
                        });

                    b.Navigation("PriorityOverride");
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyReview", b =>
                {
                    b.HasOne("CommitAhead.Domain.StudyItems.StudyItem", null)
                        .WithMany("Reviews")
                        .HasForeignKey("StudyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.StudyItems.StudyItem", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
