// <auto-generated />
using System;
using CommitAhead.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CommitAhead.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommitAheadDbContext))]
    partial class CommitAheadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommitAhead.Domain.CVPresentations.CVPresentation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("CertificationSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("certification_selections");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DateFormat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("date_format");

                    b.PrimitiveCollection<Guid[]>("EducationSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("education_selections");

                    b.PrimitiveCollection<Guid[]>("ExperienceSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("experience_selections");

                    b.Property<bool>("IncludeAddress")
                        .HasColumnType("boolean")
                        .HasColumnName("include_address");

                    b.Property<bool>("IncludeEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("include_email");

                    b.Property<bool>("IncludePhone")
                        .HasColumnType("boolean")
                        .HasColumnName("include_phone");

                    b.Property<bool>("IncludePhoto")
                        .HasColumnType("boolean")
                        .HasColumnName("include_photo");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<Guid[]>("LanguageSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("language_selections");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("locale");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("PageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("page_limit");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.PrimitiveCollection<Guid[]>("ProfileLinkSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("profile_link_selections");

                    b.PrimitiveCollection<Guid[]>("ProjectSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("project_selections");

                    b.PrimitiveCollection<Guid[]>("SkillSelections")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_selections");

                    b.Property<string>("SummaryOverrideMarkdown")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_override_markdown");

                    b.Property<string>("TargetMarket")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_market");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_role");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("template_key");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProfessionalProfileId", "OwnerUserId");

                    b.ToTable("cv_presentations", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SupabaseUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("supabase_user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupabaseUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.CertificationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CredentialId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("credential_id");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<int?>("IssuedAt")
                        .HasColumnType("integer")
                        .HasColumnName("issued_at");

                    b.Property<string>("IssuingOrganisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issuing_organisation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("certification_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.EducationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("degree");

                    b.Property<string>("DetailsMarkdown")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("details_markdown");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("institution");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<int?>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("education_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Achievements")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("achievements");

                    b.Property<string>("Client")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("employment_type");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.PrimitiveCollection<Guid[]>("SkillIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_ids");

                    b.Property<int>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.Property<string>("SummaryMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_markdown");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("work_mode");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("experience_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.LanguageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Certification")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("certification");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("language");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("proficiency");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("language_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SummaryMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("summary_markdown");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("professional_profiles", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfileLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("profile_links", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProjectEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("description_markdown");

                    b.Property<int?>("EndDate")
                        .HasColumnType("integer")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Role")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("role");

                    b.PrimitiveCollection<Guid[]>("SkillIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("skill_ids");

                    b.Property<int?>("StartDate")
                        .HasColumnType("integer")
                        .HasColumnName("start_date");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId");

                    b.ToTable("project_entries", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("NormalizedKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_key");

                    b.Property<Guid>("ProfessionalProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("professional_profile_id");

                    b.Property<string>("Proficiency")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("proficiency");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalProfileId", "NormalizedKey")
                        .IsUnique();

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("CommitAhead.Domain.CVPresentations.CVPresentation", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfessionalProfileId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.CertificationEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Certifications")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.EducationEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Education")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ExperienceEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Experience")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.LanguageEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Languages")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.HasOne("CommitAhead.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfileLink", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("ProfileLinks")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProjectEntry", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Projects")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.Skill", b =>
                {
                    b.HasOne("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", null)
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitAhead.Domain.ProfessionalProfiles.ProfessionalProfile", b =>
                {
                    b.Navigation("Certifications");

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Languages");

                    b.Navigation("ProfileLinks");

                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
